# Kernel sources configuration
# Format: <name> <repo_url> <branch>
# <name> must match a config file in configs/<name>.config
msm8974-6.12.y  https://github.com/msm8974-mainline/linux  qcom-msm8974-6.12.y
msm8x74-6.15.y  https://github.com/mlainez/linux-msm8x74   staging
